# Site settings
title: nicepls
email: akoskm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  nicepls detects insensitive words, explains the errors and suggests possible alternatives.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://akoskm.github.io/nicepls-react/" # the base hostname & protocol for your site
twitter_username: akoskm
github_username:  akoskm

# Build settings
markdown: kramdown